---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base/]
namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: stock-quant-risk
images:
  - name: stock-quant-risk
    newName: stock-quant-risk
    newTag: latest
